### ISSUE TITLE
Error logging into 3Box with a hardware wallet

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#643] opened 2020-04-01 20:22 UTC
Below from Jake Brukhman using MM + Ledger HW
`An error occured while publishing link`

![Screenshot_20200320-154825](https://user-images.githubusercontent.com/8059373/78183070-4a7cc100-7435-11ea-8588-2925706c55e6.png)

Below from Discord user kartojal also using MM + Ledger HW:
hello, im having issues for registering my profile at 3box.io/hub , trying to sign a message to create the profile via Metamask and Ledger Nano S, but is not working. Any workarounds?
tried with a normal metamask account and it worked, so i think must be something related with signature using metamask and ledger nano s
this is the error @oed 3⃣  
``` 3box.js:1169 Uncaught (in promise) Error: An error occured while publishing link:
    at t.<anonymous> (3box.js:1169)
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as throw] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:29
```
Wallet Connect is also not working with Argent wallet too, idk why.
3box.js:1155 Uncaught (in promise) Error: Link consent message must be signed before adding data, to link address to store
    at t.<anonymous> (3box.js:1155)
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as throw] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:29)

**Comment by oznekenzo** [comment] 2020-05-05 16:02
This is solved when the Hub dapp is updated to use library v 1.18.1

**Comment by michaelsena** [comment] 2020-05-14 15:45
cc @kamescg

**Comment by dazuck** [comment] 2020-06-20 16:20
@kamescg @oed where are we on this? 

As people use us with defi (RenBridge) this is becoming a more significant pattern

**Comment by oed** [comment] 2020-06-20 18:28
@dazuck 3Box works with Trezor, but ledger is not working. The issue is being tracked here: https://github.com/ethers-io/ethers.js/issues/893

**Comment by aelesbao** [comment] 2020-10-09 09:16
Seems like the linked issue was fixed. Do you have any news on when the library will be updated in 3Box? Thanks!

**Comment by oed** [comment] 2020-10-26 07:56
@aelesbao I believe this should be fixed already in the latest version of 3box-js. Are you still not able to log in and get the same error as described above?

**Comment by aelesbao** [comment] 2020-10-26 19:29
@oed I still cannot log in, but now the error message is empty

![Screenshot 2020-10-26 at 20 29 08](https://user-images.githubusercontent.com/466801/97219234-fcad1900-17c9-11eb-9e44-7fc9328bd9a9.png)

**Closed** 2021-04-28 14:54 UTC
Labels: bug
